### ISSUE TITLE
Not support async put_metrics

### ISSUE THREAD

**Issue by daniel2643** [awslabs/aws-embedded-metrics-python#115]
Hi,

 Does anyone encounter this issue? I've attempted many solutions but none of them works. 

Traceback (most recent call last):
  File "/src/executor/executor_local_test.py", line 137, in <module>
    test_mkt_knowledge_entry_langgraph(llm_model['yi'])
  File "/src/executor/executor_local_test.py", line 107, in test_mkt_knowledge_entry_langgraph
    response = generate_answer(
  File "/src/executor/executor_local_test.py", line 87, in generate_answer
    response = main.lambda_handler(event, context)
  File "/Users/wngao/Library/Python/3.9/lib/python/site-packages/aws_embedded_metrics/metric_scope/__init__.py", line 49, in wrapper
    loop = asyncio.get_event_loop()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by fernandoaguilar** [comment]
@daniel2643 pr https://github.com/awslabs/aws-embedded-metrics-python/pull/113 fixes it, we ended up forking the repo temporarily while this is merged in.

**Comment by gordonpn** [comment]
https://github.com/awslabs/aws-embedded-metrics-python/pull/113 has merged. Just pending a release.
