### ISSUE TITLE
Import of 1.0.5 yields immediate SyntaxError

### ISSUE THREAD

**Issue by mattghali** [awslabs/aws-embedded-metrics-python#62]
Environment:
```
Python 3.5.4 (v3.5.4:3f56838976, Aug  7 2017, 12:56:33) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
```

Freshly installed `aws_embedded_metrics-1.0.5-py3-none-any.whl` via `pip3 install --user aws-embedded-metrics`

any import yields a SyntaxError exception:

```
>>> import aws_embedded_metrics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ghalim/Library/Python/3.5/lib/python/site-packages/aws_embedded_metrics/__init__.py", line 16, in <module>
    from aws_embedded_metrics.metric_scope import metric_scope  # noqa: F401 E402
  File "/Users/ghalim/Library/Python/3.5/lib/python/site-packages/aws_embedded_metrics/metric_scope/__init__.py", line 14, in <module>
    from aws_embedded_metrics.logger.metrics_logger_factory import create_metrics_logger
  File "/Users/ghalim/Library/Python/3.5/lib/python/site-packages/aws_embedded_metrics/logger/metrics_logger_factory.py", line 14, in <module>
    from aws_embedded_metrics.logger.metrics_context import MetricsContext
  File "/Users/ghalim/Library/Python/3.5/lib/python/site-packages/aws_embedded_metrics/logger/metrics_context.py", line 34
    self.namespace: str = namespace or get_config().namespace or constants.DEFAULT_NAMESPACE
                  ^
SyntaxError: invalid syntax
>>> from aws_embedded_metrics import metric_scope
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ghalim/Library/Python/3.5/lib/python/site-packages/aws_embedded_metrics/__init__.py", line 16, in <module>
    from aws_embedded_metrics.metric_scope import metric_scope  # noqa: F401 E402
  File "/Users/ghalim/Library/Python/3.5/lib/python/site-packages/aws_embedded_metrics/metric_scope/__init__.py", line 14, in <module>
    from aws_embedded_metrics.logger.metrics_logger_factory import create_metrics_logger
  File "/Users/ghalim/Library/Python/3.5/lib/python/site-packages/aws_embedded_metrics/logger/metrics_logger_factory.py", line 14, in <module>
    from aws_embedded_metrics.logger.metrics_context import MetricsContext
  File "/Users/ghalim/Library/Python/3.5/lib/python/site-packages/aws_embedded_metrics/logger/metrics_context.py", line 34
    self.namespace: str = namespace or get_config().namespace or constants.DEFAULT_NAMESPACE
                  ^
SyntaxError: invalid syntax
>>> 
```

Am I doing something wrong?

**Comment by mattghali** [comment]
I suspect that this is actually a simple packaging error, with a missing `Requires-Python` attribute which would have signaled to my pip that our Python 3.5.4 was too old to handle the type annotations.

I suggest you require `>= 3.6` in your packaging.
